services:
  ocrmypdf:
    build: .
    container_name: go-ocr-pdf
    volumes:
      - ./scan:/data
      - ./languages:/languages
    environment:
      LOG_LEVEL: -4 # DEBUG (-4), INFO (0), WARN (4), and ERROR (8)
      SCAN_FOLDER: "subfolder/"
      SCAN_INTERVAL: 10 # in seconds
      CONCURRENT_JOBS: 2
    restart: unless-stopped
