name: Build and release container image
on:
  create:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      #  - run: printenv                                                          #Print all environment variables
      #  - name: Dump GitHub context
      #    env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #    run: echo "$GITHUB_CONTEXT"
      - run: apk add --update --no-cache nodejs npm
      - run: apk add --update --no-cache python3
      - uses: actions/checkout@v4
      - run: echo "IMAGE_NAME=${{github.event.repository.name}}" >> $GITHUB_ENV #IMAGE_NAME
      - run: python3 .gitea/workflows/py/getVersion.py >> $GITHUB_ENV #VERSION
      - run: python3 .gitea/workflows/py/getURL.py >> $GITHUB_ENV #URL
      - run: echo "Building and pushing image $IMAGE_NAME:$VERSION"
      - run: docker login $URL -u $GITHUB_REPOSITORY_OWNER -p ${{secrets.REGISTRY_TOKEN}}
      - run: docker build -t $URL/$GITHUB_REPOSITORY_OWNER/$IMAGE_NAME:$VERSION -t $URL/$GITHUB_REPOSITORY_OWNER/$IMAGE_NAME:latest .
      - run: docker push -a $URL/$GITHUB_REPOSITORY_OWNER/$IMAGE_NAME
